/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibraryManagementProgram.Crs;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Reader extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst, pst1;
    DefaultTableModel model;

    /**
     * Creates new form Reader
     */
    public Reader() {
        initComponents();
        setLocationRelativeTo(null);
        conn = connect.connecrDb();
        model = (DefaultTableModel) jTable1.getModel();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jdate = new javax.swing.JTextField();
        jlocal = new javax.swing.JTextField();
        jge = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jphone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1208, 740));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4), "Reader Management System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1178, 699));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Gender", "Date of birth", "Address", "Phone number"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(718, 125, 452, 550);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Name");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 190, 90, 40);

        jname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jname);
        jname.setBounds(490, 190, 210, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Gender");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 250, 90, 40);

        jdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jdate);
        jdate.setBounds(490, 310, 210, 40);

        jlocal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jlocal);
        jlocal.setBounds(490, 370, 210, 40);

        jge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Male", "Female", "Other" }));
        jge.setAlignmentX(5.0F);
        jge.setAlignmentY(5.0F);
        jge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgeActionPerformed(evt);
            }
        });
        jPanel1.add(jge);
        jge.setBounds(490, 250, 210, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Date of birth");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 310, 90, 40);

        jphone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jphone);
        jphone.setBounds(490, 430, 210, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 370, 90, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Phone number");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 430, 120, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 290, 220, 80);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 420, 220, 80);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("VIEW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 520, 220, 80);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 204, 0));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(70, 550, 220, 80);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(490, 130, 210, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("ID");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 130, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryManagementProgram/icon/hoc-tap-1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 50, 1160, 625);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jgeActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectrow = jTable1.getSelectedRow();
        if (selectrow >= 0) {
            jTextField1.setText(jTable1.getValueAt(selectrow, 0).toString());
            jname.setText(jTable1.getValueAt(selectrow, 1).toString());
            jge.setSelectedItem(jTable1.getValueAt(selectrow, 2).toString());
            jdate.setText(jTable1.getValueAt(selectrow, 3).toString());
            jlocal.setText(jTable1.getValueAt(selectrow, 4).toString());
            jphone.setText(jTable1.getValueAt(selectrow, 5).toString());

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Do you want to delete reader ? ",
                "Message",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {

            String id = jTextField1.getText();
            String sql = "select * from reader where ID=?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                rs = pst.executeQuery();
                if (rs.next()) {
                    try {
                        sql = "DELETE FROM reader WHERE (ID = ?)";
                        pst1 = conn.prepareStatement(sql);
                        pst1.setString(1, id);
                        pst1.executeUpdate();
                        pst1.close();
                        JOptionPane.showMessageDialog(null, "User was deleted");
                        jTextField1.setText("");
                        jname.setText("");
                        jge.setSelectedItem("All");
                        jdate.setText("");
                        jlocal.setText("");
                        jphone.setText("");
                        if (JOptionPane.OK_OPTION == JOptionPane.OK_OPTION) {
                            showTable();
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "User was not deleted");

                    }
                    pst.close();
                    rs.close();
                } else {
                    JOptionPane.showMessageDialog(null, "No valuse to delete");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = jTextField1.getText();
        String sql = "select * from reader where ID=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            rs = pst.executeQuery();
            if (rs.next()) {
                if (JOptionPane.showConfirmDialog(null, "Already have this User id do you want to overwrite?",
                        "Message",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                    try {
                        sql = "UPDATE `librarymanagement`.`reader` SET `Name` = ?, `Gender` = ?, `date` = ?, 'local' = ?, 'phone' = ? WHERE (`ID` = ?);";
                        pst = conn.prepareStatement(sql);
                        pst.setString(6, jTextField1.getText());
                        pst.setString(1, jname.getText());
                        pst.setString(2, (String) jge.getSelectedItem());
                        pst.setString(3, jdate.getText());
                        pst.setString(4, jlocal.getText());
                        pst.setString(5, jphone.getText());
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "User was change");
                        jTextField1.setText("");
                        jname.setText("");
                        jge.setSelectedItem("All");
                        jdate.setText("");
                        jlocal.setText("");
                        jphone.setText("");
                        if (JOptionPane.OK_OPTION == JOptionPane.OK_OPTION) {
                            showTable();
                        }
                        rs.close();
                        pst.close();

                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e);

                    }
                }
            } else {
                try {
                    sql = "Insert into reader values(?,?,?,?,?,?)";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, jTextField1.getText());
                    pst.setString(2, jname.getText());
                    pst.setString(3, (String) jge.getSelectedItem());
                    pst.setString(4, jdate.getText());
                    pst.setString(5, jlocal.getText());
                    pst.setString(6, jphone.getText());
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "New User add");
                    jTextField1.setText("");
                    jname.setText("");
                    jge.setSelectedItem("All");
                    jdate.setText("");
                    jlocal.setText("");
                    jphone.setText("");
                    if (JOptionPane.OK_OPTION == JOptionPane.OK_OPTION) {
                        showTable();
                    }
                    rs.close();
                    pst.close();

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);

                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LibraryFrame().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        view n=new view(jTextField1.getText());
        n.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showTable() {
        try {
            String sql = "Select * FROM reader";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            model.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString("ID"),
                    rs.getString("Name"),
                    rs.getString("Gender"),
                    rs.getString("date"),
                    rs.getString("local"),
                    rs.getString("phone")
                };
                model.addRow(row);

            }
            rs.close();
            st.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reader().setVisible(true);
            }
        });
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jdate;
    private javax.swing.JComboBox<String> jge;
    private javax.swing.JTextField jlocal;
    private javax.swing.JTextField jname;
    private javax.swing.JTextField jphone;
    // End of variables declaration//GEN-END:variables
    public String ID="";
}
