/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibraryManagementProgram.Crs;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class view extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst, pst1;
    DefaultTableModel model;
    private String Nid="1";

    /**
     * Creates new form view
     */
    public view(String ID) {
        initComponents();
        setLocationRelativeTo(null);
        conn = connect.connecrDb();
        model = (DefaultTableModel) jTable1.getModel();
        showTable(ID);
        Nid=ID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4), "View Reader", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Book Name", "Borrowing date", "Return date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(370, 50, 800, 624);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("ID Book");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 280, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Return date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 420, 110, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Borrowing date");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 350, 110, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(150, 280, 200, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(150, 350, 200, 40);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(150, 420, 200, 40);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(0, 0, 255));
        jToggleButton1.setText("Update");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(130, 510, 150, 50);

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(51, 204, 0));
        jToggleButton2.setText("Back");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2);
        jToggleButton2.setBounds(130, 580, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryManagementProgram/icon/hoc-tap-1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 50, 1160, 625);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectrow = jTable1.getSelectedRow();
        if (selectrow >= 0) {
            jTextField2.setText(jTable1.getValueAt(selectrow, 1).toString());
            jTextField3.setText(jTable1.getValueAt(selectrow, 2).toString());
            String st = jTable1.getValueAt(selectrow, 0).toString();
            String sql = "select IDBook from book where Title = '" + st + "'";
            try {
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                while (rs.next()) {
                    jTextField1.setText(rs.getString("IDBook"));

                }

            } catch (Exception e) {
                System.out.println(e);
            }

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        String id = jTextField1.getText();
        String sql = "select * from view where IDBook=? and ID=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            pst.setString(2, Nid);
            rs = pst.executeQuery();
            if (rs.next()) {
                if (JOptionPane.showConfirmDialog(null, "Do you want change return date ?",
                        "Message",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                    try {
                        sql = "UPDATE `librarymanagement`.`view` SET `redate` = ? WHERE (`IDBook` = ?);";
                        pst = conn.prepareStatement(sql);
                        pst.setString(2, jTextField1.getText());
                        pst.setString(1, jTextField3.getText());
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Return date was change");
                        jTextField1.setText("");
                        jTextField3.setText("");
                        jTextField2.setText("");
                        if (JOptionPane.OK_OPTION == JOptionPane.OK_OPTION) {
                            showTable(Nid);
                        }
                        rs.close();
                        pst.close();

                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e);

                    }
                }
            } else {
                try {
                    sql = "Insert into view values(?,?,?,?)";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, Nid);
                    pst.setString(2, jTextField1.getText());
                    pst.setString(3, jTextField2.getText());
                    pst.setString(4, jTextField3.getText());
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "New borrow add");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    if (JOptionPane.OK_OPTION == JOptionPane.OK_OPTION) {
                        showTable(Nid);
                    }
                    rs.close();
                    pst.close();

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);

                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showTable(String a) {
        try {
            String sql = "select Title, paydate, redate "
                    + "from view v inner join book b "
                    + "on v.IDBook = b.IDBook where (ID='"+a+"')";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            model.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString("Title"),
                    rs.getString("paydate"),
                    rs.getString("redate")
                };
                model.addRow(row);

            }
            rs.close();
            st.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            /*public void run() {
                new view(Nid).setVisible(true);
            }*/
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables

}
