/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai8;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Bai8Frame extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst, pst1;
    DefaultTableModel model;
    public int chose = 0;
    public String temp1, tempm, tempp, tempc, id;

    /**
     * Creates new form Bai8Frame
     */
    public Bai8Frame() {
        initComponents();
        jFrame2.setLocationRelativeTo(null);
        setLocationRelativeTo(null);
        conn = connect.connecrDb();
        model = (DefaultTableModel) jTable1.getModel();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame2 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        math = new javax.swing.JTextField();
        phys = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        che = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jFrame2.setTitle("Edit from");
        jFrame2.setMinimumSize(new java.awt.Dimension(400, 350));
        jFrame2.setPreferredSize(new java.awt.Dimension(400, 350));
        jFrame2.setResizable(false);

        jPanel2.setMinimumSize(new java.awt.Dimension(380, 308));

        jLabel5.setText("Name");

        jLabel6.setText("Math");

        jLabel7.setText("Physics");

        jLabel8.setText("Chemistry");

        jButton6.setText("Ok");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(math))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phys))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(che))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(math, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phys, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(che, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management");
        setMinimumSize(new java.awt.Dimension(794, 565));
        setPreferredSize(new java.awt.Dimension(794, 565));
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Math", "Phys", "Chem", "Aver"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Insert");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectrow = jTable1.getSelectedRow();
        if (selectrow >= 0) {
            jFrame2.setVisible(true);
            jFrame2.setTitle("Edit form");
            chose = 1;
            name.setText(temp1);
            math.setText(tempm);
            phys.setText(tempp);
            che.setText(tempc);
            name.setEditable(true);
            math.setEditable(true);
            phys.setEditable(true);
            che.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn sinh viên");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        int selectrow = jTable1.getSelectedRow();
        if (selectrow >= 0) {
            jFrame2.setVisible(true);
            jFrame2.setTitle("Delete form");
            chose = 2;
            name.setEditable(false);
            math.setEditable(false);
            phys.setEditable(false);
            che.setEditable(false);
            name.setText(temp1);
            math.setText(tempm);
            phys.setText(tempp);
            che.setText(tempc);

        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn sinh viên");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jFrame2.setVisible(true);
        jFrame2.setTitle("Insert form");
        chose = 3;
        name.setText("");
        math.setText("");
        phys.setText("");
        che.setText("");
        name.setEditable(true);
        math.setEditable(true);
        phys.setEditable(true);
        che.setEditable(true);

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jFrame2.setVisible(false);
        chose = 0;
        temp1 = "";
        tempm = "";
        tempp = "";
        tempc = "";
        name.setText("");
        math.setText("");
        phys.setText("");
        che.setText("");
        name.setEditable(true);
        math.setEditable(true);
        phys.setEditable(true);
        che.setEditable(true);
        showTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectrow = jTable1.getSelectedRow();
        if (selectrow >= 0) {
            temp1 = (jTable1.getValueAt(selectrow, 1).toString());
            tempm = (jTable1.getValueAt(selectrow, 2).toString());
            tempp = (jTable1.getValueAt(selectrow, 3).toString());
            tempc = (jTable1.getValueAt(selectrow, 4).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (chose == 1) {
            if (JOptionPane.showConfirmDialog(null, "Do you want to chane this student ? ",
                    "Message",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                String sql = "select * from students where name=?";
                try {
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, temp1);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        try {
                            sql = "UPDATE students SET name = ?, math = ?, phys = ?, chem = ? WHERE (name =?);";
                            pst1 = conn.prepareStatement(sql);
                            pst1.setString(1, name.getText());
                            pst1.setString(2, math.getText());
                            pst1.setString(3, phys.getText());
                            pst1.setString(4, che.getText());
                            pst1.setString(5, temp1);
                            pst1.executeUpdate();
                            pst1.close();
                            JOptionPane.showMessageDialog(null, "Đã thay đổi ");
                            jFrame2.setVisible(false);
                            chose = 0;
                            name.setText("");
                            math.setText("");
                            phys.setText("");
                            che.setText("");
                            name.setEditable(true);
                            math.setEditable(true);
                            phys.setEditable(true);
                            che.setEditable(true);
                            showTable();
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "student was not deleted");
                            jFrame2.setVisible(false);
                            chose = 0;
                            name.setText("");
                            math.setText("");
                            phys.setText("");
                            che.setText("");
                            name.setEditable(true);
                            math.setEditable(true);
                            phys.setEditable(true);
                            che.setEditable(true);
                            showTable();
                        }
                        pst.close();
                        rs.close();
                    } else {
                        JOptionPane.showMessageDialog(null, "No data to delete");
                        jFrame2.setVisible(false);
                        chose = 0;
                        name.setText("");
                        math.setText("");
                        phys.setText("");
                        che.setText("");
                        name.setEditable(true);
                        math.setEditable(true);
                        phys.setEditable(true);
                        che.setEditable(true);
                        showTable();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } else if (chose == 2) {
            if (JOptionPane.showConfirmDialog(null, "Do you want to delete this student ? ",
                    "Message",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                String sql = "select * from students where name=?";
                try {
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, temp1);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        try {
                            sql = "DELETE FROM students WHERE (name = ?)";
                            pst1 = conn.prepareStatement(sql);
                            pst1.setString(1, temp1);
                            pst1.executeUpdate();
                            pst1.close();
                            JOptionPane.showMessageDialog(null, "student was deleted");
                            jFrame2.setVisible(false);
                            chose = 0;
                            name.setText("");
                            math.setText("");
                            phys.setText("");
                            che.setText("");
                            name.setEditable(true);
                            math.setEditable(true);
                            phys.setEditable(true);
                            che.setEditable(true);
                            showTable();
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "student was not deleted");
                            jFrame2.setVisible(false);
                            chose = 0;
                            name.setText("");
                            math.setText("");
                            phys.setText("");
                            che.setText("");
                            name.setEditable(true);
                            math.setEditable(true);
                            phys.setEditable(true);
                            che.setEditable(true);
                            showTable();
                        }
                        pst.close();
                        rs.close();
                    } else {
                        JOptionPane.showMessageDialog(null, "No data to delete");
                        jFrame2.setVisible(false);
                        chose = 0;
                        name.setText("");
                        math.setText("");
                        phys.setText("");
                        che.setText("");
                        name.setEditable(true);
                        math.setEditable(true);
                        phys.setEditable(true);
                        che.setEditable(true);
                        showTable();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } else if (chose == 3) {
            if (JOptionPane.showConfirmDialog(null, "Do you want to insert this student ? ",
                    "Message",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                String sql = "select * from students where name=?";
                try {
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, temp1);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Đã có student này");
                        jFrame2.setVisible(false);
                        chose = 0;
                        name.setText("");
                        math.setText("");
                        phys.setText("");
                        che.setText("");
                        name.setEditable(true);
                        math.setEditable(true);
                        phys.setEditable(true);
                        che.setEditable(true);
                        showTable();
                    } else {
                        try {
                            sql = "INSERT INTO `students` (`name`, `math`, `phys`, `chem`) VALUES (?, ?,?,?);";
                            pst1 = conn.prepareStatement(sql);
                            pst1.setString(1, name.getText());
                            pst1.setString(2, math.getText());
                            pst1.setString(3, phys.getText());
                            pst1.setString(4, che.getText());
                            pst1.executeUpdate();
                            pst1.close();
                            JOptionPane.showMessageDialog(null, "Đã thêm student");
                            jFrame2.setVisible(false);
                            chose = 0;
                            name.setText("");
                            math.setText("");
                            phys.setText("");
                            che.setText("");
                            name.setEditable(true);
                            math.setEditable(true);
                            phys.setEditable(true);
                            che.setEditable(true);
                            showTable();
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "Không thể thêm học sinh này");
                            jFrame2.setVisible(false);
                            chose = 0;
                            name.setText("");
                            math.setText("");
                            phys.setText("");
                            che.setText("");
                            name.setEditable(true);
                            math.setEditable(true);
                            phys.setEditable(true);
                            che.setEditable(true);
                            showTable();
                        }
                        pst.close();
                        rs.close();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showTable() {
        try {
            String sql = "Select * FROM students";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            model.setRowCount(0);
            String av;
            id = "1";
            while (rs.next()) {
                av = String.valueOf(((float) (rs.getInt("math") + rs.getInt("phys") + rs.getInt("chem"))) / 3);
                String[] row = new String[]{
                    id,
                    rs.getString("name"),
                    rs.getString("math"),
                    rs.getString("phys"),
                    rs.getString("chem"),
                    av,};
                model.addRow(row);
                id = (String.valueOf(Integer.parseInt(id) + 1));
                System.out.println(id);
            }
            rs.close();
            st.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai8Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai8Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai8Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai8Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai8Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField che;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField math;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phys;
    // End of variables declaration//GEN-END:variables
}
